### ISSUE TITLE
Create a QA-CLI PoC for producing primary quality metric

### ISSUE THREAD

**Issue by ameteiko** [kyma-project/qa-cli#6] opened 2022-12-08 09:41 UTC
- [x] Conceptualise the application architecture
- [x] Create application carcass according to the chosen architecture
- [ ] Implement application building scripts
- [ ] Cover the codebase with unit tests
- [ ] Cover the codebase with acceptance tests
- [ ] Configure the quality gateways for the source code

### Basic components implementation:

- [x] Cobra adapter
- [x] Metric controller
- [x] External commands runner
- [ ] Metric output parser
- [ ] Metric processor
- [ ] Report builder
- [ ] CLI adaptor

**Comment by ameteiko** [comment] 2022-12-08 09:42
Proposed Ports-and-Adapters architecture
![Ports-and-adapters](https://user-images.githubusercontent.com/1386964/206412897-d1708e7c-9155-4205-bfbe-82d2c0934b3d.png)

**Comment by tobiscr** [comment] 2023-02-08 13:06
Closing this issue as the QA dashboard got stopped caused by the Kyma internal team re-arrangement.

**Closed as completed by tobiscr** 2023-02-08 13:06 UTC
